// <auto-generated />
using System;
using System.Collections.Generic;
using ER.Melksaz.Modules.IdentityModule.Infrastructure.Persistence.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ER.Melksaz.Modules.IdentityModule.Infrastructure._migrations
{
    [DbContext(typeof(IdentityWriteDbContext))]
    partial class IdentityWriteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Identity")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ER.Melksaz.BuildingBlocks.Persistence.Models.OutboxMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsIntegrationEvent")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("OccuredOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ProcessedOn")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages", "Identity");
                });

            modelBuilder.Entity("ER.Melksaz.Modules.IdentityModule.Domain.Aggregates.UserAggregate.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("varchar(26)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(2000)");

                    b.Property<byte[]>("Email_Hash")
                        .HasColumnType("varbinary(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("varchar(2000)");

                    b.Property<byte[]>("Mobile_Hash")
                        .HasColumnType("varbinary(50)");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasColumnType("varchar(2000)");

                    b.Property<byte[]>("NationalCode_Hash")
                        .HasColumnType("varbinary(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Password", "ER.Melksaz.Modules.IdentityModule.Domain.Aggregates.UserAggregate.User.Password#PasswordHash", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<byte[]>("Hash")
                                .IsRequired()
                                .HasColumnType("varbinary(50)")
                                .HasColumnName("Password_Hash");

                            b1.Property<byte[]>("Salt")
                                .IsRequired()
                                .HasColumnType("varbinary(50)")
                                .HasColumnName("Password_Salt");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Email_Hash")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_EmailHash_Unique")
                        .HasFilter("[Email_Hash] IS NOT NULL");

                    b.HasIndex("Mobile_Hash")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_MobileHash_Unique")
                        .HasFilter("[Mobile_Hash] IS NOT NULL");

                    b.HasIndex("NationalCode_Hash")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_NationalCodeHash_Unique")
                        .HasFilter("[NationalCode_Hash] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("[Username] <> ''");

                    b.ToTable("Users", "Identity");

                    b.HasAnnotation("HashMappings", new[] { ("Mobile", "Mobile_Hash"), ("Email", "Email_Hash"), ("NationalCode", "NationalCode_Hash") });
                });
#pragma warning restore 612, 618
        }
    }
}
