<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Specifications\Builders\SpecificationBuilder_Old.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DynamicQuery\DQ.Abstraction\DQ.Abstraction.csproj" />
  </ItemGroup>

</Project>
